#!/usr/bin/env python3
"""Run focused Kyd Project Runtime V1 R1 conformance fixtures."""

import copy
import hashlib
import json
import subprocess
import sys
import tempfile
from pathlib import Path


START = "<!-- KYD_RUNTIME_DATA_START -->"
END = "<!-- KYD_RUNTIME_DATA_END -->"
PROJECT = "runtime-conformance-fixture"
RUNTIME_VERSION = "KPR-V1"
AUTHORITY_ID = "FIXTURE-AUTH"


def write_runtime_file(root, relative_path, title, data):
    path = root / relative_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f"# {title}\n\n{START}\n{json.dumps(data, indent=2)}\n{END}\n",
        encoding="utf-8",
    )


def contract(depends_on=None, authority_id=AUTHORITY_ID):
    return {
        "goal": "Exercise one deterministic Runtime conformance boundary.",
        "depends_on": depends_on or [],
        "authority_inputs": {
            "mandatory": [{"authority_id": authority_id, "version": "R1"}],
            "reference": [],
        },
        "touches": {
            "routes": [],
            "components": [],
            "files": ["docs/runtime-fixture-output.md"],
            "data": [],
            "api": [],
            "other": [],
        },
        "shared_resources": [],
        "gates_required": ["FIXTURE_GATE"],
        "allowed_changes": ["Fixture-only documentation output"],
        "forbidden_changes": ["Any change outside the fixture root"],
        "acceptance": ["The declared fixture invariant is exercised"],
        "verification": ["Run tools/kyd_runtime_validate.py"],
    }


def task(task_id, status, depends_on=None, authority_id=AUTHORITY_ID):
    return {
        "task_id": task_id,
        "title": f"Fixture task {task_id}",
        "type": "VALIDATION",
        "status": status,
        "contract": contract(depends_on, authority_id),
    }


def trace(task_id, status="VERIFIED"):
    return {
        "trace_id": f"TRACE-{task_id}",
        "source_id": AUTHORITY_ID,
        "task_id": task_id,
        "implementation": "Synthetic fixture state prepared inside a temporary directory.",
        "verification": ["Validator outcome checked by the conformance runner"],
        "evidence": ["Temporary fixture generated by run_runtime_conformance.py"],
        "status": status,
    }


def build_fixture(root, *, tasks, traces, gates=None, current_task="NONE"):
    (root / "AGENTS.md").write_text(
        "# Fixture Agent Rules\n\nUse repository-controlled Runtime state only.\n",
        encoding="utf-8",
    )
    authority_path = root / "docs/authority/FIXTURE_AUTHORITY.md"
    authority_path.parent.mkdir(parents=True, exist_ok=True)
    authority_path.write_text(
        "# Fixture Authority R1\n\nSynthetic conformance fixture authority.\n",
        encoding="utf-8",
    )
    authority_hash = hashlib.sha256(authority_path.read_bytes()).hexdigest()

    project_index = {
        "runtime_schema": "kyd.project-index.v1",
        "project": PROJECT,
        "runtime_version": RUNTIME_VERSION,
        "authorities": [
            {
                "authority_id": AUTHORITY_ID,
                "area": "runtime-conformance",
                "name": "Fixture Authority",
                "path": "docs/authority/FIXTURE_AUTHORITY.md",
                "kind": "AUTHORITY",
                "version": "R1",
                "status": "FROZEN",
                "sha256": authority_hash,
                "purpose": "Synthetic conformance input",
            }
        ],
    }
    current_state = {
        "runtime_schema": "kyd.current-state.v1",
        "project": PROJECT,
        "runtime_version": RUNTIME_VERSION,
        "starter_version": "NOT_APPLICABLE",
        "delivery_profile": "CONFORMANCE",
        "product_freeze_version": "NOT_APPLICABLE",
        "ui_freeze_version": "NOT_APPLICABLE",
        "current_phase": "RUNTIME_CONFORMANCE",
        "current_task": current_task,
        "last_verified_commit": "fixture",
        "blocked": {"status": False, "blocker_ids": []},
        "gates": gates
        if gates is not None
        else [
            {
                "gate_id": "FIXTURE_GATE",
                "status": "PASS",
                "evidence": ["docs/authority/FIXTURE_AUTHORITY.md"],
            }
        ],
        "known_deviations": [],
        "next_task": "NONE",
        "release_status": "NOT_READY",
    }
    feature_matrix = {
        "runtime_schema": "kyd.feature-matrix.v1",
        "project": PROJECT,
        "runtime_version": RUNTIME_VERSION,
        "features": [],
    }
    task_index = {
        "runtime_schema": "kyd.task-index.v1",
        "project": PROJECT,
        "runtime_version": RUNTIME_VERSION,
        "tasks": tasks,
    }
    implementation_trace = {
        "runtime_schema": "kyd.implementation-trace.v1",
        "project": PROJECT,
        "runtime_version": RUNTIME_VERSION,
        "traces": traces,
    }

    write_runtime_file(root, "docs/PROJECT_INDEX.md", "PROJECT_INDEX", project_index)
    write_runtime_file(root, "docs/CURRENT_STATE.md", "CURRENT_STATE", current_state)
    write_runtime_file(
        root, "docs/product/FEATURE_MATRIX.md", "FEATURE_MATRIX", feature_matrix
    )
    write_runtime_file(root, "docs/tasks/TASK_INDEX.md", "TASK_INDEX", task_index)
    write_runtime_file(
        root,
        "docs/execution/IMPLEMENTATION_TRACE.md",
        "IMPLEMENTATION_TRACE",
        implementation_trace,
    )
    if current_task != "NONE":
        selected = next(item for item in tasks if item["task_id"] == current_task)
        current_task_data = {
            "runtime_schema": "kyd.current-task.v1",
            "project": PROJECT,
            "runtime_version": RUNTIME_VERSION,
            "task_id": selected["task_id"],
            "status": selected["status"],
            "contract": copy.deepcopy(selected["contract"]),
            "verification_evidence": [],
        }
        write_runtime_file(
            root, "docs/tasks/CURRENT_TASK.md", "CURRENT_TASK", current_task_data
        )


def fixture_positive(root):
    build_fixture(
        root,
        tasks=[task("TASK-BASE", "VERIFIED")],
        traces=[trace("TASK-BASE")],
    )


def fixture_dependency_not_verified(root):
    build_fixture(
        root,
        tasks=[
            task("TASK-BASE", "BLOCKED"),
            task("TASK-WORK", "READY", ["TASK-BASE"]),
        ],
        traces=[trace("TASK-BASE", "BLOCKED")],
        current_task="TASK-WORK",
    )


def fixture_dependency_cycle(root):
    build_fixture(
        root,
        tasks=[
            task("TASK-A", "BLOCKED", ["TASK-B"]),
            task("TASK-B", "BLOCKED", ["TASK-A"]),
        ],
        traces=[trace("TASK-A", "BLOCKED"), trace("TASK-B", "BLOCKED")],
    )


def fixture_missing_authority(root):
    build_fixture(
        root,
        tasks=[task("TASK-WORK", "READY", authority_id="MISSING-AUTH")],
        traces=[],
        current_task="TASK-WORK",
    )


def fixture_frozen_hash_mismatch(root):
    build_fixture(
        root,
        tasks=[task("TASK-BASE", "VERIFIED")],
        traces=[trace("TASK-BASE")],
    )
    authority = root / "docs/authority/FIXTURE_AUTHORITY.md"
    authority.write_text(authority.read_text(encoding="utf-8") + "mutated\n", encoding="utf-8")


def fixture_pass_gate_missing_evidence(root):
    build_fixture(
        root,
        tasks=[task("TASK-BASE", "VERIFIED")],
        traces=[trace("TASK-BASE")],
        gates=[{"gate_id": "FIXTURE_GATE", "status": "PASS", "evidence": []}],
    )


def fixture_pass_gate_blank_evidence(root):
    build_fixture(
        root,
        tasks=[task("TASK-BASE", "VERIFIED")],
        traces=[trace("TASK-BASE")],
        gates=[{"gate_id": "FIXTURE_GATE", "status": "PASS", "evidence": [""]}],
    )


def fixture_verified_task_missing_trace(root):
    build_fixture(root, tasks=[task("TASK-BASE", "VERIFIED")], traces=[])


def fixture_trace_missing_source_id(root):
    invalid_trace = trace("TASK-BASE")
    del invalid_trace["source_id"]
    build_fixture(
        root,
        tasks=[task("TASK-BASE", "VERIFIED")],
        traces=[invalid_trace],
    )


def fixture_trace_missing_implementation(root):
    invalid_trace = trace("TASK-BASE")
    del invalid_trace["implementation"]
    build_fixture(
        root,
        tasks=[task("TASK-BASE", "VERIFIED")],
        traces=[invalid_trace],
    )


def fixture_fresh_session(root):
    build_fixture(
        root,
        tasks=[
            task("TASK-BASE", "VERIFIED"),
            task("TASK-WORK", "READY", ["TASK-BASE"]),
        ],
        traces=[trace("TASK-BASE")],
        current_task="TASK-WORK",
    )


CASES = [
    ("positive_valid_closeout", fixture_positive, "closeout", True, "KYD_RUNTIME_VALIDATE: PASS"),
    ("negative_dependency_not_verified", fixture_dependency_not_verified, "execution", False, "dependency TASK-BASE status=BLOCKED, requires VERIFIED"),
    ("negative_dependency_cycle", fixture_dependency_cycle, "closeout", False, "dependency cycle:"),
    ("negative_missing_authority", fixture_missing_authority, "execution", False, "unknown mandatory authority MISSING-AUTH"),
    ("negative_frozen_hash_mismatch", fixture_frozen_hash_mismatch, "closeout", False, "FROZEN sha256 mismatch"),
    ("negative_pass_gate_missing_evidence", fixture_pass_gate_missing_evidence, "closeout", False, "PASS without evidence"),
    ("negative_pass_gate_blank_evidence", fixture_pass_gate_blank_evidence, "closeout", False, "PASS evidence entries must be non-empty strings"),
    ("negative_verified_task_missing_trace", fixture_verified_task_missing_trace, "closeout", False, "VERIFIED task without evidence-bearing VERIFIED trace"),
    ("negative_trace_missing_source_id", fixture_trace_missing_source_id, "closeout", False, "missing required fields ['source_id']"),
    ("negative_trace_missing_implementation", fixture_trace_missing_implementation, "closeout", False, "missing required fields ['implementation']"),
    ("fresh_session_execution", fixture_fresh_session, "execution", True, "EXECUTION_ALLOWED = TRUE"),
]


def main():
    repo_root = Path(__file__).resolve().parents[2]
    validator = repo_root / "tools/kyd_runtime_validate.py"
    failures = []
    positive_count = 0
    negative_count = 0

    for name, builder, mode, should_pass, expected_text in CASES:
        with tempfile.TemporaryDirectory(prefix=f"kyd-{name}-") as temp:
            fixture_root = Path(temp)
            builder(fixture_root)
            result = subprocess.run(
                [sys.executable, str(validator), "--root", str(fixture_root), "--mode", mode],
                text=True,
                capture_output=True,
                check=False,
            )
        output = result.stdout + result.stderr
        outcome_matches = (result.returncode == 0) if should_pass else (result.returncode != 0)
        passed = outcome_matches and expected_text in output
        if should_pass:
            positive_count += 1
        else:
            negative_count += 1
        print(
            f"{name}: {'PASS' if passed else 'FAIL'} "
            f"(expected={'PASS' if should_pass else 'FAIL'}, exit={result.returncode})"
        )
        if not passed:
            failures.append(name)
            print(output.rstrip())

    print(
        f"SUMMARY: positive={positive_count} negative={negative_count} "
        f"failed={len(failures)}"
    )
    if failures:
        print("CONFORMANCE_RESULT: FAIL")
        return 1
    print("CONFORMANCE_RESULT: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
